# Generated by Django 4.2.30 on 2026-05-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='review_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
